version: '3'
services:
  frontend:
    build:
      context: ./frontend # Path to the frontend application directory
      dockerfile: Dockerfile
    image: jeffdiers/burrito-shop-frontend:latest
    ports:
      - "3000:3000"
  backend:
    build:
      context: ./backend # Path to the backend application directory
      dockerfile: Dockerfile
    image: jeffdiers/burrito-shop-backend:latest
    environment:
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - API_KEY=$API_KEY
    ports:
      - "4000:4000"
