name: Docker Build, Push, and Deploy

on:
  push:
    branches:
      - main # Change to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker buildx create --use
          docker buildx build -t jeffdiers/burrito-shop:latest . --push
        env:
          DOCKER_CLI_AARCH64: docker

  deploy:
    runs-on: self-hosted # Use your EC2 instance here

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install Docker
        run: |
          # Install Docker
          sudo yum update
          sudo yum install -y docker

      - name: Stop and Remove Existing Container
        run: |
          # Stop the existing container if it's running
          if [ "$(sudo docker ps -aq -f name=burrito-shop)" ]; then
            sudo docker stop burrito-shop
          fi

          # Remove the existing container if it exists
          if [ "$(sudo docker ps -aq -f name=burrito-shop)" ]; then
            sudo docker rm burrito-shop
          fi

      - name: Remove Old Docker Image # delete old image to save space on ec2 instance
        run: |
          # Remove the old Docker image if it exists
          if [ "$(sudo docker images -aq jeffdiers/burrito-shop:latest)" ]; then
            sudo docker rmi jeffdiers/burrito-shop:latest
          fi

      - name: Pull Docker image
        run: sudo docker pull jeffdiers/burrito-shop:latest

      - name: Run Docker container
        run: |
          sudo docker run -d --name burrito-shop --network host -e DB_HOST=localhost -e DB_PORT=5432 -e DB_USER=${{ secrets.DB_USER }} -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} -e DB_NAME=${{ secrets.DB_NAME }} -e API_KEY=${{ secrets.API_KEY }} jeffdiers/burrito-shop:latest
